[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
viaIR = false
initial_balance = '0xd3c21bcecceda1000000'
optimizer_runs = 1000000

[fuzz]
# runs = 1000000
# max_test_rejects = 70000000
runs = 256

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
